name: jacksonsburger
description: An application for burger place
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  fluttertoast: ^8.2.2
  cloud_firestore: ^4.8.2
  cupertino_icons: ^1.0.5
  firebase_auth: ^4.10.1
  firebase_core: ^2.14.0
  firebase_database: 10.2.7
  google_sign_in: ^6.1.5
  math_expressions: ^2.4.0
  provider:
  fl_chart: ^0.60.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0


dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  change_app_package_name: ^1.1.0

flutter:
  uses-material-design: true
  assets:
    - lib/images/
