// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUCuO2msTGHyUR-4890lfpl_d2jFwpF3Y',
    appId: '1:831409974500:web:ecb3998ee57967a84e90f1',
    messagingSenderId: '831409974500',
    projectId: 'jacksonsburger',
    authDomain: 'jacksonsburger.firebaseapp.com',
    storageBucket: 'jacksonsburger.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFrYoYKriUY83wmOMbV4sxN2m5Jsdk67k',
    appId: '1:831409974500:android:84183588bb0745894e90f1',
    messagingSenderId: '831409974500',
    projectId: 'jacksonsburger',
    storageBucket: 'jacksonsburger.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOAyE1d-a1U-mGRYJJ-reIV0w_CB0kfQE',
    appId: '1:831409974500:ios:f14f3dc48c7fa1694e90f1',
    messagingSenderId: '831409974500',
    projectId: 'jacksonsburger',
    storageBucket: 'jacksonsburger.appspot.com',
    iosBundleId: 'com.example.jacksonsburger',
  );
}
